cmd: npm start
targets:
  build-smartcontracts:
    cmd: "npm run build"
  flatten-smartcontracts:
    cmd: "npx waffle flatten"
  test-smartcontracts:
    cmd: "npm run test"
  migrate-development:
    cmd: "npm run migrate"
  migrate-integration:
    cmd: "npm run migrate --network 6226"
  app-dev:
    cmd: "cd app && npm run dev"
  app-build:
    cmd: "cd app && npm run build"
